path: focus
train: images/train
val: images/val
test:

names:
  0: person
  1: bicycle
  2: car
  3: motorcycle
  4: airplane
  5: bus
  6: train
  7: truck
  8: boat
  9: traffic light
  10: cat
  11: dog
  12: apple
  13: banana
  14: chair
  15: tv
  16: laptop
  17: book